job_family = [
    "Business",
    "Clerical",
    "Contact Centre",
    "Customer Service",
    "Information Technology",
    "Safety",
    "Sales"
]
job_level = [
    "Director",
    "Entry-level",
    "Executive",
    "Front Line Manager",
    "General Population",
    "Graduate",
    "Manager",
    "Mid-professional",
    "Professional Individual Contributor",
    "Supervisor"
]
industry = [
    "Banking/Finance",
    "Healthcare",
    "Hospitality",
    "Insurance",
    "Manufacturing",
    "Oil & Gas",
    "Retail",
    "Telecommunication"
]
languages = [
    "English",
    "Spanish",
    "French",
    "German",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Japanese",
    "Korean",
    "Portuguese",
    "Italian",
    "Dutch",
    "Russian",
    "Arabic",
    "Hindi",
    "Bengali",
    "Urdu",
    "Turkish",
    "Vietnamese",
    "Polish",
    "Romanian",
    "Thai",
    "Hebrew",
    "Swedish",
    "Norwegian",
    "Finnish",
    "Greek",
    "Czech",
    "Hungarian",
    "Indonesian",
    "Malay",
    "Filipino (Tagalog)",
    "Ukrainian",
    "Persian (Farsi)",
    "Swahili",
    "Tamil",
    "Telugu",
    "Marathi",
    "Kannada",
    "Gujarati",
    "Punjabi",
    "Serbian",
    "Croatian",
    "Slovak",
    "Bulgarian",
    "Malayalam",
    "Latvian",
    "Lithuanian",
    "Estonian",
    "Slovenian",
    "Arabic",
    "Bulgarian",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Czech",
    "Danish",
    "Dutch",
    "English (Australia)",
    "English (Canada)",
    "English (International)",
    "English (Malaysia)",
    "English (Singapore)",
    "English (South Africa)",
    "English (USA)",
    "Estonian",
    "Finnish",
    "French (Belgium)",
    "French (Canada)",
    "German",
    "Greek",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Italian",
    "Japanese",
    "Korean",
    "Latvian",
    "Lithuanian",
    "Malay",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Slovak",
    "Spanish",
    "Swedish",
    "Turkish",
    "Ukrainian"
]
job_category = [
    "Architecture and Engineering",
    "Arts, Design, and Media",
    "Building and Grounds Cleaning and Maintenance",
    "Business and Financial Operations",
    "Computer and Mathematical",
    "Community and Social Services",
    "Construction and Extraction",
    "Education, Training, and Library",
    "Farming, Fishing, and Forestry",
    "Food Preparation and Serving Related",
    "Healthcare Practitioners and Technical",
    "Health and Environmental Science",
    "Healthcare Support",
    "Legal",
    "Management and Leadership",
    "Production",
    "Protective Service",
    "Sales and Related",
    "Skilled Electrical, Mechanical, and Industrial",
    "Office and Administrative Support",
    "Personal Care and Service",
    "Transportation and Material Moving"
]